config/routes.rb
YouFood::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :orders do
    resources :orders_starters, :orders_dishes, :orders_deserts do
      member do
        post 'taken'
        post 'ready'
      end
    end
    
    post 'call', :on => :member
  end
  
  resources :dinning_rooms do 
    resources :room_zones do
      resources :tables do 
        resources :orders
      end
    end
    
    resources :cuisines
    
  end
  
  resources :waiters
  

  root :to => 'dinning_rooms#index'

end

app/models/room_zone.rb
class RoomZone < ActiveRecord::Base
  attr_accessible :name, :tables_attributes, :dinning_room_id
  
  has_many :tables
  belongs_to :dinning_room
  has_many :waiters
  
  accepts_nested_attributes_for :tables
  
end

app/controllers/room_zones_controller.rb
class RoomZonesController < ApplicationController
  # GET /room_zones
  # GET /room_zones.json
  def index
    @room_zones = RoomZone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @room_zones }
    end
  end

  # GET /room_zones/1
  # GET /room_zones/1.json
  def show
    @room_zone = RoomZone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room_zone }
    end
  end

  # GET /room_zones/new
  # GET /room_zones/new.json
  def new
    @room_zone = RoomZone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room_zone }
    end
  end

  # GET /room_zones/1/edit
  def edit
    @room_zone = RoomZone.find(params[:id])
  end

  # POST /room_zones
  # POST /room_zones.json
  def create
    @room_zone = RoomZone.new(params[:room_zone])

    respond_to do |format|
      if @room_zone.save
        format.html { redirect_to @room_zone, notice: 'Room zone was successfully created.' }
        format.json { render json: @room_zone, status: :created, location: @room_zone }
      else
        format.html { render action: "new" }
        format.json { render json: @room_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /room_zones/1
  # PUT /room_zones/1.json
  def update
    @room_zone = RoomZone.find(params[:id])

    respond_to do |format|
      if @room_zone.update_attributes(params[:room_zone])
        format.html { redirect_to @room_zone, notice: 'Room zone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_zones/1
  # DELETE /room_zones/1.json
  def destroy
    @room_zone = RoomZone.find(params[:id])
    @room_zone.destroy

    respond_to do |format|
      format.html { redirect_to room_zones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/room_zones_helper.rb
module RoomZonesHelper
end

app/views/room_zones/_form.html.erb
<%= form_for @room_zone, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dinning_room_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :dinning_room_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                room_zones_path, :class => 'btn' %>
  </div>
<% end %>

app/views/room_zones/edit.html.erb
<%- model_class = @room_zone.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/room_zones/index.html.erb
<%- model_class = RoomZone.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:dinning_room_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @room_zones.each do |room_zone| %>
      <tr>
        <td><%= link_to room_zone.id, room_zone_path(room_zone) %></td>
        <td><%= room_zone.name %></td>
        <td><%= room_zone.dinning_room_id %></td>
        <td><%=l room_zone.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_room_zone_path(room_zone), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      room_zone_path(room_zone),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_room_zone_path,
            :class => 'btn btn-primary' %>

app/views/room_zones/new.html.erb
<%- model_class = @room_zone.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/room_zones/show.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Home</a> <span class="divider">/</span>
  </li>
  <li>
    <%= link_to @room_zone.dinning_room.name, @room_zone.dinning_room %> <span class="divider">/</span>
  </li>
  <li class="active"><%= @room_zone.name %></li>
</ul>
<br />
	<div class="span10 offset1">
		<ul class="thumbnails">
		<% @room_zone.tables.each do |table| %>
			<li class="span2">
				<div class="thumbnail">
					<%= link_to image_tag("http://placehold.it/160x120&text=#{table.name}"), dinning_room_room_zone_table_url(@room_zone.dinning_room, @room_zone, table) %>
					<div class="caption">
						<h5><%= table.name %></h5>
					</div>
				</div>
			</li>
		<% end -%>
		</ul>
</div>