config/routes.rb
YouFood::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :orders do
    resources :orders_starters, :orders_dishes, :orders_deserts do
      member do
        post 'taken'
        post 'ready'
      end
    end
    
    post 'call', :on => :member
  end
  
  resources :dinning_rooms do 
    resources :room_zones do
      resources :tables do 
        resources :orders
      end
    end
    
    resources :cuisines
    
  end
  
  resources :waiters
  

  root :to => 'dinning_rooms#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :table_id, :ready, :taken, :deserts, :starters, :dishes, :starters_attributes, :dishes_attributes, :deserts_attributes, :orders_starters_attributes, :orders_dishes_attributes, :orders_deserts_attributes
  
  belongs_to :table  
  
  has_many :orders_deserts, :dependent => :destroy
  has_many :orders_starters, :dependent => :destroy
  has_many :orders_dishes, :dependent => :destroy
  has_many :deserts, :through => :orders_deserts
  has_many :starters, :through => :orders_starters
  has_many :dishes, :through => :orders_dishes
  
  accepts_nested_attributes_for :orders_starters
  accepts_nested_attributes_for :orders_dishes
  accepts_nested_attributes_for :orders_deserts
  
  def price    
    ['starters', 'dishes', 'deserts'].collect { |course| self.send("orders_#{course}").collect { |x| x.quantity*x.send(course.singularize).price }.inject { |sum,x| sum+x } }.inject { |a, b| a + b}
  end
  
  %w(starters dishes deserts).each do |nee|
    define_method("#{nee}_left") { self.send("orders_#{nee}").not_ready.count }
  end
  
  def self.has_starters_left
    Order.where(:start)
  end
  
  # w00ts
  scope :not_ready, lambda {
    joins(:orders_deserts, :orders_starters, :orders_dishes).where('orders_starters.ready = false OR orders_deserts.ready = false OR orders_dishes.ready = false').uniq
  }
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.not_ready

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @orders }
    # end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])
  
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new
    @order.table_id = params[:table_id]

    @food_menu = FoodMenu.active.first

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  # def edit
  #   @order = Order.find(params[:id])
  # end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    @order.table_id = params[:table_id]

    respond_to do |format|
      if @order.save
        # PrivatePub.publish_to('/orders/new', @order)
        
        # format.js {render :partial => 'create'}
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }     
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  # def update
  #   @order = Order.find(params[:id])
  # 
  #   respond_to do |format|
  #     if @order.update_attributes(params[:order])
  #       format.html { redirect_to @order, notice: 'Order was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @order.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
  
  def call 
    @table = Table.find(params[:id])
  end
  
  
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :taken, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :taken, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ready, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :ready, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn' %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<h3>Order #<%= order.id %></h3>

<table class="table table-striped table-bordered table-condensed">
<thead>
	<tr>
		<th>Type</th>
		<th>Name</th>
		<th>Quantity</th>
		<th>State</th>
	</tr>
<thead>

<% ['starters', 'dishes', 'deserts'].each do |course| %>

	<thead id="order-<%= order.id %>-<%=  course %>-thead">
	<tr>
		<th><%= course.capitalize %></th>
		<th colspan="3"></th>
	</tr>

	</thead>
	<tbody  id="order-<%= order.id %>-<%=  course %>-tbody">
	<% order.send("orders_#{course}").each do |ox| %>
		<tr>
			<td>
			<td><%= ox.send(course.singularize).name %></td>
			<td><%= ox.quantity %></td>
			<td class="order-state"><%= form_tag "/orders/#{order.id}/orders_#{course}/#{ox.id}/ready", remote: true, html: {:class => 'form-inline'} do %><input type="submit" class="btn btn-success btn-mini <%= 'disabled' if ox.ready %>" id="orders_<%= course %>_<%= ox.id %>_ready" value="Ready" /><% end -%><%= form_tag "/orders/#{order.id}/orders_#{course}/#{ox.id}/taken", remote: true, html: {:class => 'form-inline'} do %><input type="submit" class="btn btn-primary btn-mini <%= 'disabled' if ox.taken %>" id="orders_<%= course %>_<%= ox.id %>_taken" value="Taken" /><% end -%></td>
		</tr>
	<% end -%>
	</tbody>

<% end %>

</table>

app/views/orders/call.js.erb
<% publish_to "/zone/#{@table.room_zone.id}" do %>
	$("#notifications").append("<div class=\"alert alert-error\"><a class=\"close\" data-dismiss=\"alert\" href=\"#\">×</a>Table <strong><%= @table.name %></strong> is calling.</div>");
<% end %>

app/views/orders/create.js.erb
<% publish_to "/orders/new" do %>
	$('#orders-list').append("<%= j render(@order) %>")
<% end %>

app/views/orders/edit.html.erb
<%- model_class = @order.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orders/index.html.erb
<div id="orders-list">

<%= render @orders %>

</div>

app/views/orders/new.html.erb
<%- model_class = @order.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%# render :partial => 'form' %>

<div class="row">

<% ['starters', 'dishes', 'deserts'].each do |x| %>

<div id="<%= x %>" class="span12">
	      <h2><%= x %></h2>
	      <ul class="thumbnails">
	
		<% for z in @food_menu.send(x) %>
	        <li class="span3 <%= "#{x}-#{z.id}" %>">
	          <div class="thumbnail">
	            <%= image_tag z.image.url(:medium) %>
	            <div class="caption">
	              <h5><%= z.name %></h5>
	              <p><%= z.description %></p>
				  <input type="hidden" name="order[orders_<%= x %>_attributes][][<%= x.singularize %>_id]" value="<%= z.id %>">
	
	              <p><div class="input-prepend food-pricing"><button class="btn btn-primary add-food" type="button">+</button><button class="btn rem-food" type="button">-</button><input class="span1 uneditable-input food-qty" name="order[orders_<%= x %>_attributes][][quantity]" size="8" type="text" value="0" data-food="<%= x %>" data-id="<%= z.id %>"><span class="price badge"><%= z.price%>&euro;</span></p>
	            </div></div>
	          </div>
	        </li>
	        <%- end -%>
	      </ul>
	
</div>

<% end %>

<div id="resume" class="span12">
	<h2>Resume</h2>
	<%= form_tag dinning_room_room_zone_table_orders_url do |f| %>
		<ul class="thumbnails">
		</ul>
		<button type="submit" class="btn btn-primary">Checkout</button>
	<% end %>
</div>

app/views/orders/show.html.erb
<div class="hero-unit">
	<h1>Thanks !</h1>
	<p>Your order's cooking is in progress, you can track its status here (it will auto-update)</p>
	<hr />
	<%= render :partial => 'order_show', :locals => { :order => @order } %>
	
</div>

<% publish_to "/orders/new" do %>
	$('#orders-list').append("<%= j render(@order) %>");
<% end %>

<% publish_to "/zone/#{@order.table.room_zone.id}" do %>
	$("#notifications").append("<div class=\"alert alert-warning\"><a class=\"close\" data-dismiss=\"alert\" href=\"#\">×</a>Table <strong><%= @order.table.name %></strong> has made an order.</div>");
<% end %>