config/routes.rb
YouFood::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :orders do
    resources :orders_starters, :orders_dishes, :orders_deserts do
      member do
        post 'taken'
        post 'ready'
      end
    end
    
    post 'call', :on => :member
  end
  
  resources :dinning_rooms do 
    resources :room_zones do
      resources :tables do 
        resources :orders
      end
    end
    
    resources :cuisines
    
  end
  
  resources :waiters
  

  root :to => 'dinning_rooms#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  belongs_to :dinning_room
  # attr_accessible :title, :body
  
  attr_accessible :name
end

app/models/desert.rb
class Desert < ActiveRecord::Base
  attr_accessible :name, :food_type, :description, :price, :image
  
  has_attached_file :image, :styles => { :medium => "238x238>", :thumb => "100x100>" }
  
  
  belongs_to :food_menu
end

app/models/dinning_room.rb
class DinningRoom < ActiveRecord::Base
  attr_accessible :name, :address, :city, :zipcode, :room_zones_attributes, :cuisines_attributes
  
  has_many :room_zones
  has_many :cuisines
  
  accepts_nested_attributes_for :room_zones, :cuisines
  
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :name, :food_type, :description, :price, :image
  
  has_attached_file :image, :styles => { :medium => "238x238>", :thumb => "100x100>" }
  
  
  belongs_to :food_menu
end

app/models/food_menu.rb
class FoodMenu < ActiveRecord::Base
  attr_accessible :name, :price, :image, :starters_attributes, :dishes_attributes, :deserts_attributes, :is_active
  
  has_many :starters
  has_many :dishes
  has_many :deserts
  
  accepts_nested_attributes_for :starters
  accepts_nested_attributes_for :dishes
  accepts_nested_attributes_for :deserts
  
  has_attached_file :image, :styles => { :medium => "238x238>", :thumb => "100x100>" }
  
  scope :active, where(:is_active => true)
  scope :inactive, where(:is_active => false)
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :table_id, :ready, :taken, :deserts, :starters, :dishes, :starters_attributes, :dishes_attributes, :deserts_attributes, :orders_starters_attributes, :orders_dishes_attributes, :orders_deserts_attributes
  
  belongs_to :table  
  
  has_many :orders_deserts, :dependent => :destroy
  has_many :orders_starters, :dependent => :destroy
  has_many :orders_dishes, :dependent => :destroy
  has_many :deserts, :through => :orders_deserts
  has_many :starters, :through => :orders_starters
  has_many :dishes, :through => :orders_dishes
  
  accepts_nested_attributes_for :orders_starters
  accepts_nested_attributes_for :orders_dishes
  accepts_nested_attributes_for :orders_deserts
  
  def price    
    ['starters', 'dishes', 'deserts'].collect { |course| self.send("orders_#{course}").collect { |x| x.quantity*x.send(course.singularize).price }.inject { |sum,x| sum+x } }.inject { |a, b| a + b}
  end
  
  %w(starters dishes deserts).each do |nee|
    define_method("#{nee}_left") { self.send("orders_#{nee}").not_ready.count }
  end
  
  def self.has_starters_left
    Order.where(:start)
  end
  
  # w00ts
  scope :not_ready, lambda {
    joins(:orders_deserts, :orders_starters, :orders_dishes).where('orders_starters.ready = false OR orders_deserts.ready = false OR orders_dishes.ready = false').uniq
  }
  
end

app/models/orders_desert.rb
class OrdersDesert < ActiveRecord::Base
  attr_accessible :desert_id, :quantity
  
  scope :ready, where(ready: true)
  scope :not_ready, where(ready: false)
  scope :taken, where(taken: true)
  scope :not_taken, where(taken: false)
  
  belongs_to :order
  belongs_to :desert
end

app/models/orders_dish.rb
class OrdersDish < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :dish_id, :quantity
  
  scope :ready, where(ready: true)
  scope :not_ready, where(ready: false)
  scope :taken, where(taken: true)
  scope :not_taken, where(taken: false)
  
  belongs_to :order
  belongs_to :dish
end

app/models/orders_starter.rb
class OrdersStarter < ActiveRecord::Base
  attr_accessible :starter_id, :quantity

  scope :ready, where(ready: true)
  scope :not_ready, where(ready: false)
  scope :taken, where(taken: true)
  scope :not_taken, where(taken: false)

  belongs_to :order
  belongs_to :starter
end

app/models/room_zone.rb
class RoomZone < ActiveRecord::Base
  attr_accessible :name, :tables_attributes, :dinning_room_id
  
  has_many :tables
  belongs_to :dinning_room
  has_many :waiters
  
  accepts_nested_attributes_for :tables
  
end

app/models/starter.rb
class Starter < ActiveRecord::Base
  attr_accessible :name, :food_type, :description, :price, :image
  
  has_attached_file :image, :styles => { :medium => "238x238>", :thumb => "100x100>" }
  
  
  belongs_to :food_menu
end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :capacity, :room_zone_id, :name
  
  belongs_to :room_zone
  has_many :orders
  
end

app/models/waiter.rb
class Waiter < ActiveRecord::Base
  attr_accessible :name, :room_zone_id
  
  belongs_to :room_zone
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dinning_rooms_helper.rb
module DinningRoomsHelper
end

app/helpers/orders_dishes_helper.rb
module OrdersDishesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/room_zones_helper.rb
module RoomZonesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/tables/_form.html.erb
<%= form_for @table, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :capacity, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :capacity, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :room_zone_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :room_zone_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tables_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<%- model_class = @table.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tables/index.html.erb
<%- model_class = Table.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:capacity) %></th>
      <th><%= model_class.human_attribute_name(:room_zone_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= link_to table.id, table_path(table) %></td>
        <td><%= table.capacity %></td>
        <td><%= table.room_zone_id %></td>
        <td><%= table.name %></td>
        <td><%=l table.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_table_path(table), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      table_path(table),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_table_path,
            :class => 'btn btn-primary' %>

app/views/tables/new.html.erb
<%- model_class = @table.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tables/show.html.erb
<div class="hero-unit">
	<h1>Welcome</h1>
	<p>This week, we feature a special Menu : <strong><%= FoodMenu.active.last.name %></strong></p>
	<br />
	<p>You can right now start to order thanks to our interactive system or call for a waiter.</p>
		<ul class="thumbnails"id="table-welcome">
			<li class="span4">
				<button>
				<%= link_to image_tag("http://placehold.it/360x268&text=Order"), new_dinning_room_room_zone_table_order_url(@table.room_zone.dinning_room, @table.room_zone, @table), :class => 'thumbnail' %>
				</button>
			</li>
			<li class="span4">
				<%= form_tag call_order_url(@table.id), remote: true do %>
					<button type="submit">
					<%= image_tag "http://placehold.it/360x268&text=Call", :class => 'thumbnail'%>
					</button>
				<% end %>
			</li>
		</ul>
</div>