config/routes.rb
YouFood::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :orders do
    resources :orders_starters, :orders_dishes, :orders_deserts do
      member do
        post 'taken'
        post 'ready'
      end
    end
    
    post 'call', :on => :member
  end
  
  resources :dinning_rooms do 
    resources :room_zones do
      resources :tables do 
        resources :orders
      end
    end
    
    resources :cuisines
    
  end
  
  resources :waiters
  

  root :to => 'dinning_rooms#index'

end

app/models/dinning_room.rb
class DinningRoom < ActiveRecord::Base
  attr_accessible :name, :address, :city, :zipcode, :room_zones_attributes, :cuisines_attributes
  
  has_many :room_zones
  has_many :cuisines
  
  accepts_nested_attributes_for :room_zones, :cuisines
  
end

app/controllers/dinning_rooms_controller.rb
class DinningRoomsController < ApplicationController
  # GET /dinning_rooms
  # GET /dinning_rooms.json
  def index
    @dinning_rooms = DinningRoom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dinning_rooms }
    end
  end

  # GET /dinning_rooms/1
  # GET /dinning_rooms/1.json
  def show
    @dinning_room = DinningRoom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dinning_room }
    end
  end

  # GET /dinning_rooms/new
  # GET /dinning_rooms/new.json
  def new
    @dinning_room = DinningRoom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dinning_room }
    end
  end

  # GET /dinning_rooms/1/edit
  def edit
    @dinning_room = DinningRoom.find(params[:id])
  end

  # POST /dinning_rooms
  # POST /dinning_rooms.json
  def create
    @dinning_room = DinningRoom.new(params[:dinning_room])

    respond_to do |format|
      if @dinning_room.save
        format.html { redirect_to @dinning_room, notice: 'Dinning room was successfully created.' }
        format.json { render json: @dinning_room, status: :created, location: @dinning_room }
      else
        format.html { render action: "new" }
        format.json { render json: @dinning_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dinning_rooms/1
  # PUT /dinning_rooms/1.json
  def update
    @dinning_room = DinningRoom.find(params[:id])

    respond_to do |format|
      if @dinning_room.update_attributes(params[:dinning_room])
        format.html { redirect_to @dinning_room, notice: 'Dinning room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dinning_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinning_rooms/1
  # DELETE /dinning_rooms/1.json
  def destroy
    @dinning_room = DinningRoom.find(params[:id])
    @dinning_room.destroy

    respond_to do |format|
      format.html { redirect_to dinning_rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dinning_rooms_helper.rb
module DinningRoomsHelper
end

app/views/dinning_rooms/_form.html.erb
<%= form_for @dinning_room, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zipcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zipcode, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dinning_rooms_path, :class => 'btn' %>
  </div>
<% end %>

app/views/dinning_rooms/edit.html.erb
<%- model_class = @dinning_room.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dinning_rooms/index.html.erb
<ul class="breadcrumb">
  <li>
    <a href="active">Home</a> 
  </li>
</ul>
	<div class="span10 offset1">
		<ul class="thumbnails">
		<% @dinning_rooms.each do |dinning_room| %>
			<li class="span2">
				<div class="thumbnail">
					<%= link_to image_tag("http://placehold.it/160x120&text=#{dinning_room.name}"), dinning_room %>
					<div class="caption">
						<h5><%= dinning_room.name %></h5>
						<p><%= dinning_room.address %><p>
						<p><%= dinning_room.zipcode %> <%= dinning_room.city %></p>
					</div>
				</div>
			</li>
		<% end -%>
		</ul>
	</div>

app/views/dinning_rooms/new.html.erb
<%- model_class = @dinning_room.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dinning_rooms/show.html.erb
<ul class="breadcrumb">
  <li>
    <a href="/">Home</a> <span class="divider">/</span>
  </li>
  <li class="active"><%= @dinning_room.name %></li>
</ul>
<br />
	<div class="span10 offset1">
		<ul class="thumbnails">
		<% @dinning_room.room_zones.each do |room_zone| %>
			<li class="span2">
				<div class="thumbnail">
					<%= link_to image_tag("http://placehold.it/160x120&text=#{room_zone.name}"), dinning_room_room_zone_url(@dinning_room, room_zone) %>
					<div class="caption">
						<h5><%= room_zone.name %></h5>
					</div>
				</div>
			</li>
		<% end -%>
		</ul>
</div>